name: Chess Analysis CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: ['3.4.1']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Install dependencies
      run: bundle install
    
    - name: Set up database
      run: ruby db/migrate.rb
    
    - name: Run tests
      run: bundle exec rspec --format documentation
    
    - name: Run RuboCop
      run: bundle exec rubocop
      continue-on-error: true

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1'
        bundler-cache: true
    
    - name: Install bundler-audit
      run: gem install bundler-audit
    
    - name: Update vulnerability database
      run: bundle audit --update
    
    - name: Run security audit
      run: bundle audit --check